USE [DB_VIDEO_PLATAFORM]
GO
/****** Object:  Table [dbo].[Tb_Chat]    Script Date: 28/09/2022 21:03:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tb_Chat](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NomeSala] [varchar](255) NULL,
	[ID_Usuario] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Tb_Historico_Chat]    Script Date: 28/09/2022 21:03:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tb_Historico_Chat](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Conversa] [varchar](max) NULL,
	[DataInicio] [datetime] NULL,
	[DataFim] [datetime] NULL,
	[ID_Chat] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Tb_Perfil]    Script Date: 28/09/2022 21:03:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tb_Perfil](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Descricao] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Tb_Permissao] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Tb_Usuario]    Script Date: 28/09/2022 21:03:34 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tb_Usuario](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](255) NULL,
	[ID_Perfil] [int] NULL,
	[LoginUsu] [varchar](50) NULL,
	[Senha] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Tb_Chat]  WITH CHECK ADD  CONSTRAINT [fk_ChatUsu] FOREIGN KEY([ID_Usuario])
REFERENCES [dbo].[Tb_Usuario] ([ID])
GO
ALTER TABLE [dbo].[Tb_Chat] CHECK CONSTRAINT [fk_ChatUsu]
GO
ALTER TABLE [dbo].[Tb_Historico_Chat]  WITH CHECK ADD  CONSTRAINT [fk_HistChat] FOREIGN KEY([ID_Chat])
REFERENCES [dbo].[Tb_Chat] ([ID])
GO
ALTER TABLE [dbo].[Tb_Historico_Chat] CHECK CONSTRAINT [fk_HistChat]
GO
ALTER TABLE [dbo].[Tb_Usuario]  WITH CHECK ADD  CONSTRAINT [fk_UsuPerfil] FOREIGN KEY([ID_Perfil])
REFERENCES [dbo].[Tb_Perfil] ([ID])
GO
ALTER TABLE [dbo].[Tb_Usuario] CHECK CONSTRAINT [fk_UsuPerfil]
GO
